version: '3'

services :
  app:
    build:
        context: ./
        dockerfile: Dockerfile
    volumes:
        - ./service:/var/www/service
    ports:
        - '8081:80'
    links:
      - db:db
    env_file:
      ./docker-dev/php/.env_dev
    entrypoint: sh -c '/var/www/docker-php-entrypoint.sh'
    tty: true
    stdin_open: true

  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      LANG: C.UTF-8
    volumes:
      - ./docker-dev/mysql/conf.d:/etc/mysql/conf.d
    env_file:
      ./docker-dev/mysql/.env_db
    ports:
      - '3306:3306'